
/* This file is generated by glib-mkenums, do not modify it. This code is licensed under the same license as the containing project. Note that it links to GLib, so must comply with the LGPL linking clauses. */

#ifndef LSM_DOM_ENUM_TYPES_H
#define LSM_DOM_ENUM_TYPES_H

#include <glib-object.h>

G_BEGIN_DECLS
/* Enumerations from "lsmdebug.h" */
#define LSM_TYPE_DEBUG_LEVEL	(lsm_debug_level_get_type())
GType lsm_debug_level_get_type	(void) G_GNUC_CONST;
/* Enumerations from "lsmdomnode.h" */
#define LSM_TYPE_DOM_NODE_TYPE	(lsm_dom_node_type_get_type())
GType lsm_dom_node_type_get_type	(void) G_GNUC_CONST;
G_END_DECLS

#endif /* LSM_DOM_ENUM_TYPES_H */

/* Generated data ends here */

